# Generated by Django 5.1 on 2025-08-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=200, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Preco'),
        ),
    ]
