# Generated by Django 5.1 on 2025-09-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0004_avaliacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='texto_review',
            new_name='review_text',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='id_evaluation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
